name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-lib-project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Check linting
      run: yarn lint

    - name: Build typescript & flow
      run: yarn build

  check-example-project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Check linting
      run: yarn lint

    - name: Check typescript
      run: yarn tsc