name: CI

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Check linting
      run: yarn lint

    - name: Build typescript & flow
      run: yarn build

    - name: Example lint
      run: cd KakaoLoginExample && yarn && yarn lint

    - name: Example tsc
      run: yarn tsc

    - name: Example test
      run: yarn test --coverage
